version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - sql-db
      - nosql-db

  sql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Singh@54321
    ports:
      - "5432:5432"

  nosql-db:
    image: mongo:latest
    ports:
      - "27017:27017"
